### ISSUE TITLE
[Feat] Sticker Page

### ISSUE THREAD

**Issue by flareseek** [keepgoingLikelion/meringue-FE#2]
## Summary
- 스티커를 붙이는 뷰 제작

## Goals
- 해당 글의 내용과 반응 스티커를 확인할 수 있다.

## Plan
- 일단은 컴포넌트들 작성을 해서 보여지는 뷰를 작성합니다.

## TODO
- [x] 카드에 스티커 방지
- [x] sticker 배열 Key
- [x] 같은 위치 방지
