### ISSUE TITLE
[Feat] Calendar Component

### ISSUE THREAD

**Issue by yeahzee0421** [keepgoingLikelion/meringue-FE#3]
## Summary
- 캘린더 컴포넌트 개발 

## Goals
- 유저가 어떤 '감정'의 글을 썼는지 캘린더로 한눈에 확인할 수 있다. 또한 날짜를 클릭했을 때 해당 날짜에 작성한 글과 다른 사람들이 남기고 간 스티커들을 볼 수 있다. 

## Plan
- zustand store 를 이용한 날짜 상태 관리 
- no use react-calendar library

## TODO
- [x] 라이브러리 없이 캘린더 구현 
- [x] 캘린더 날짜 Date 타입으로 받아올 수 있게 수정하기
- [x] 작성된 글이 있다면 글의 카테고리와 icon을 불러오기
- [x] api 구조 파악하고 카테고리에 따른 icon fetch 해오기
- [x] 날짜 click하면 그날 작성된 글 불러오기  
- [x] 깨진 달력 css 수정................... 하 .·´¯`(>▂<)´¯`·. 

## Additional Context
