### ISSUE TITLE
[Feat] 스티커 종류 컴포넌트 

### ISSUE THREAD

**Issue by flareseek** [keepgoingLikelion/meringue-FE#5]
## Summary
- 스티커를 고를 수 있는 컴포넌트 구현

## Goals
- 사용자가 원하는 스티커를 붙일 수 있도록 함

## Plan
- 사용자가 + 버튼을 누르면 스티커 종류를 나타내는 뷰를 보여주고, 스티커를 클릭후 화면을 클릭하면 골랐던 스티커를 클릭한 위치에 붙임

## TODO
- [x] + 버튼 누를시 컴포넌트 띄우기
- [x] 스티커 종류 컴포넌트 만들기
- [x] 스티커 클릭시 컴포넌트 내리기
- [x] 화면 클릭시 백엔드에 request
