### ISSUE TITLE
[Feat] UserLog 기능 개발

### ISSUE THREAD

**Issue by yeahzee0421** [keepgoingLikelion/meringue-FE#6]
## Summary
- 그땐머랭? user log 기능 개발

## Goals
- 자신이 스티커를 남긴 글을 감정 카테고리 별로 확인할 수 있다. 

## Plan
- emotionType: Integer를 서버에서 가져와 로컬에서 각 감정 이모지에 mapping하여 이모지 보여줌
- api fetch시 react-query 이용 
- card 형식으로 글을 보여줌> 컴포넌트화 필요해보임. 

## TODO
- [x] useLikedPosts store 생성, api 가져오기
- [x] 감정 이모지 매핑
- [x] 각 이모지를 누르면 해당 emotionType에 해당하는 글 card 형식으로 보여주기 > 새로운 UserLog 페이지 추가 예정

## Additional Context
- 아자아자

**Comment by yeahzee0421** [comment]
vite가 실행이 안되는 오류가 발생했는데 package-lock.json 파일을 삭제 후 npm install하니 해결되었습니다. 아마 react-router-dom 설치를 시도했었는데, 이때 의존성에 문제가 발생했던 것 같습니다.
